name: CI - Build and Push Docker Images

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 047776567953.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingassistantservice
          - loadgenerator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./src/${{ matrix.service }}
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/online-boutique/${{ matrix.service }}:latest
            ${{ env.ECR_REGISTRY }}/online-boutique/${{ matrix.service }}:${{ github.sha }}